### PR TITLE
Prepare for migration to next  release of Miden crypto

### PR DESCRIPTION
**Pull request by Al-Kindi-0**
## Describe your changes
Mostly `no-std` issues and Falcon DSA.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Comment by bobbinth** [comment]
`miden-crypto` [v0.9.0](https://crates.io/crates/miden-crypto) is now on crates.io.

**Comment by Al-Kindi-0** [comment]
> `miden-crypto` [v0.9.0](https://crates.io/crates/miden-crypto) is now on crates.io.

Updated the PR accordingly. There is a `clippy` warning which I am not not sure about the best way to handle it.

**Review by bitwalker — APPROVED** [review]
LGTM!

Rebasing my PR on this shouldn't be too bad, probably not worth trying to introduce any additional formatting changes here though, or it will make conflicts harder to untangle. I did a quick review of the commits in my PR, and I don't have a specific commit where I introduced formatting changes explicitly, so I think any such changes fell out of modifying a file for other reasons, and the formatter changing the file in the process. Of course, with the number of files touched, that means there is a fair amount of formatting noise in that PR.

Once this is merged, I'll rebase my PR on it and that should make future rebases less problematic.

**Comment by bitwalker** [comment]
> There is a `clippy` warning which I am not not sure about the best way to handle it.

I would add a `#[allow(dead_code)]` annotation on that field for now, but if it is truly never read, then it can probably just be removed entirely, along with any code that writes to it.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I pushed a small commit which fixes the clippy warning. In the longer run, we should remove this field as I don't think we need it any more (I believe it was used for auxiliary trace hints, but these are now done differently).

One thing I wonder about: maybe we should handle signature generation code via events and have the decorator only for reading the signature from the advice provider. I'll try to write up an issue about this.

**Pull request merged**
