### PR TITLE
Integrate new `ilog2` and `cto` instructions into MMR

### PR DESCRIPTION
**Pull request by Overcastan**
After implementation of the new `ilog2` and `cto` instructions it became possible to use them directly in the implementation of the MMR. 
This PR removes the special implementations of `ilog2` and `cto` instructions in the MMR and uses identical assembly instructions instead.

### CODE REVIEW

**Review by hackaugusto — APPROVED** [review]
neat. lgtm

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

**Comment by bobbinth** [comment]
One question: does this break anything in `miden-base`? (i don't think it should, but would be good to double-check)

**Comment by Overcastan** [comment]
I checked: no, it doesn't break anything, I managed to build the `miden-base` repo and successfully run all tests.

**Pull request merged**
