### PR TITLE
docs: program docs update

### PR DESCRIPTION
**Pull request by frisitano**
## Describe your changes

I'm not sure if "attempt to" or "try to" has any meaning in the context of program execution but if not then it may be good to remove them to make the passage clearer.  This PR removes the instances of this language in the example program execution description.

### CODE REVIEW

**Review by hackaugusto — APPROVED** [review]
LGTM :)

**Comment by grjte** [comment]
I think the point here was that if the execution of the first block fails then the VM won't continue. @frisitano are you thinking that this is implicit and therefore doesn't need to be said?

**Comment by bobbinth** [comment]
I agree with @grjte - execution of a given block is not guaranteed to succeed - so, the language is there to highlight it.

**Comment by frisitano** [comment]
When I read this initially I wasn't sure if there was a logical distinction between blocks that were "tried" / "attempted" and blocks that were "executed" and that confused me a little.  Having consistent language across all block descriptions would be clearer in my opinion.  The failure cases are documented on the same page so maybe it's not necessary?

**Comment by bobbinth** [comment]
> > Miden VM consumes programs in a form of a Merkelized Abstract Syntax Tree (MAST). This tree is a binary tree where each node is a code block. The VM starts execution at the root of the tree, and attempts to recursively execute each required block according to its semantics. If the execution of a code block fails, the VM halts at that point and no further blocks are executed. A set of currently available blocks and their execution semantics are described below.
> 
> After that, I would keep the current section as it is (reverting your changes). We could also add the "attempts" language to the description of each code block if you think that would help, but that might not be necessary.
> 
> What do you think @frisitano @bobbinth?

I like this intro! As for the other parts - I'm fine either way.

**Comment by frisitano** [comment]
I think explicitly explaining the failure case in the intro, as you have done, helps a lot.  It's probably sufficient alone without modifications to other parts of the text.

**Review by grjte — APPROVED** [review]
Looks good! Thanks for catching this so we could clarify

**Pull request merged**
