### PR TITLE
docs: document stack state for ext2 instructions

### PR DESCRIPTION
**Pull request by hackaugusto**
## Describe your changes

As the PR title says.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Comment by hackaugusto** [comment]
Current render:

image

with this change:

image

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! One small thing: we should probably update line 59 as well as `q` no longer refers to an irreducible polynomial.

**Comment by hackaugusto** [comment]
remove the mention to `q`, now it renders like this:

image

**Comment by hackaugusto** [comment]
Oh, I missed that, thanks @Al-Kindi-0 ! Fixed it:

image

**Review by Overcastan — APPROVED** [review]
Looks great, thank you @hackaugusto!

**Pull request merged**
