### PR TITLE
chore: add windows to ci tests

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

**Comment by vlopes11** [comment]
Seems windows will slow considerably the CI (completion time of stable in ubuntu is ~4mins and windows is ~6.5mins)

We can alternatively just leave this PR here and merge `next` to this branch before releasing to `main`, only to check if windows is broken. Or, we just merge it :dagger:

**Comment by bobbinth** [comment]
I guessed if it passed here, then we are good with the `stdlib` build script, right? If so, I'm fine skipping windows in CI for now. Or, I wonder if we can configure it so that we run windows build only when merging into `main`?

**Comment by vlopes11** [comment]
It passed so it's guaranteed to work, yes! The suggestion to run just for target main is very good; will make that change later

**Comment by vlopes11** [comment]
@bobbinth to my surprise, the slash instead of backslash worked on windows. Maybe it's only a win-2022 thing?

**Comment by bobbinth** [comment]
Based on [this](https://stackoverflow.com/questions/38428561/difference-between-forward-slash-and-backslash-in-file-path) it seems like Windows should understand both (at least modern versions). So, my thinking is that we could do the following:

- Keep a single `let bytes = include_bytes!("../assets/std.masl");` (the way you have now).
- Add tests on Windows to the CI but only when we merge into `main`.

What do you think?

**Comment by vlopes11** [comment]
@bobbinth @grjte ready for review!

**Review by grjte — APPROVED** [review]
It looks good to me! Thanks @vlopes11

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

One question: why does it show un-formatted string in the CI results for the skipped task?

Screenshot 2022-12-15 at 4 03 43 PM

**Comment by vlopes11** [comment]
@bobbinth looks like a flaw in GH. Seems they take the raw name instead of rendering templates for skipped tasks. We can just hardcode the name there since it's a single item matrix tho

**Comment by bobbinth** [comment]
@vlopes11 - yeah, let's hardcode then.

**Pull request merged**
