### PR TITLE
refactor: remove 8 bit portion of the range checker

### PR DESCRIPTION
**Pull request by tohrnii**
## Describe your changes
Addressing #395. Simplifies the range checker design by removing the 8-bit segment of the range checker table. This however increases the minimum length of the trace since we can no longer use the 8-bit table after this change to allow jumps of $2^8$ and instead can only allow jumps of 8 because that requires a constraint of degree 9. The following constraint ensures consistency of the range checker table.

$$
\prod_{i=0}^8 (\Delta v - i) = 0
$$

- [X] Modify the shape of the trace and trace generation
- [X] Update AIR constraints
- [X] Update tests
- [ ] Update docs
- [ ] Modify testing methodology to reduce test run-times.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Comment by bobbinth** [comment]
If I'm reading test runtimes correctly, it seems that they increased by 30% - 40% - is this right? If so, maybe it's not too bad. If there are some simple ways to reduce them, we can do that now - but if not, we can leave that for future PRs.

**Comment by tohrnii** [comment]
> If I'm reading test runtimes correctly, it seems that they increased by 30% - 40% - is this right?

On M1 with 8 cores, it goes from ~47 seconds to ~500 seconds for integration tests.

**Comment by bobbinth** [comment]
> On M1 with 8 cores, it goes from ~47 seconds to ~500 seconds for integration tests.

Is this via `make test` command?

**Comment by tohrnii** [comment]
> Is this via make test command?

Ah, that was using `cargo test` without any flags. Using `make test` you're right it's around 30% increase.

**Comment by bobbinth** [comment]
> Ah, that was using `cargo test` without any flags. Using `make test` you're right it's around 30% increase.

`make test` is what we use to run tests in CI (and also locally) - so, I'd base analysis on these numbers. What do absolute numbers look like, btw?

**Comment by tohrnii** [comment]
@bobbinth Sorry, I ran it on the wrong branch earlier. It actually goes from ~4 to ~60 seconds.

**Comment by bobbinth** [comment]
> It actually goes from ~4 to ~60 seconds.

Hmmm - could you double-check? A 15x increase seems rather high - I would have expected an 8x increase in the worst possible case.

**Comment by tohrnii** [comment]
> Hmmm - could you double-check? A 15x increase seems rather high - I would have expected an 8x increase in the worst possible case.

Yeah, makes sense. The runtime number seems correct (checked 5 times). Let me look into it and get back.

**Comment by tohrnii** [comment]
Closing this PR since this design increases the minimum trace length to $2^14$ which is probably fine for the rollup but more than what we want for the VM.

**Pull request closed without merging**
