### PR TITLE
Compute Rescue Prime Hash over 32 -bytes

### PR DESCRIPTION
**Pull request by itzmeanjan**
Miden assembly routine for computing Rescue Prime hash over 32 -bytes input, represented in terms of 4 Miden field elements. 

> **Note**
Cost of 1-to-1 hash routine is 21 -cycles, while computing 2-to-1 hashing using Rescue Prime costs us 16 -cycles, for which we've one dedicated instruction. 

Read https://github.com/0xPolygonMiden/examples/issues/14 for understanding why we decided to add this routine.

### CODE REVIEW

**Comment by bobbinth** [comment]
I think there is a more efficient way to do hash chain computations (see https://github.com/0xPolygonMiden/examples/issues/14#issuecomment-1335680162) - so, I'm not sure we actually need this.

I do have a couple of questions, however:
- I think your code actually takes 19 cycles (rather than 21) - or am I missing something?
- I am not sure this makes sense as an `stdlib` procedure. But I wonder if it would make sense as a separate assembly instruction.

**Comment by itzmeanjan** [comment]
> I think your code actually takes 19 cycles (rather than 21) - or am I missing something?

It should be 19, I should subtract 2 because of codeblock. 



> * I am not sure this makes sense as an `stdlib` procedure. But I wonder if it would make sense as a separate assembly instruction.

I'd like to keep it, though no objection related to form i.e. either stdlib routine or assembly instruction.

**Comment by itzmeanjan** [comment]
We're looking for your suggestion on how to name Miden VM native hash function/ permutation, see https://github.com/maticnetwork/miden/issues/590

**Comment by grjte** [comment]
@bobbinth @itzmeanjan my understanding is that this is the PR with the function that we want to turn into the `hash` assembly operation, although there's quite a bit more included in this. How would you prefer to move forward? We could move just the `rescue_prime::hash_1to1` change (and test) into a separate PR where it is moved into the assembly operations as `hash` instead.

In that case either @itzmeanjan or @0xKanekiKen could do this work. Please let me know what you think.

**Comment by bobbinth** [comment]
@grjte - yep, I think this approach makes sense.

**Comment by bobbinth** [comment]
Superseded by #700

**Pull request closed without merging**
