### PR TITLE
chore: increment all crates version to v0.10.0

### PR DESCRIPTION
**Pull request by greenhat**
This PR increments all crates versions to v0.10.0 so that compiler crates be able to reference next published VM crates to test the compiler crates publishing.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

**Comment by greenhat** [comment]
I cannot figure out why `changelog` GA is red. I've restarted the failed job multiple times, checked the script, re-applied the label.

**Comment by bobbinth** [comment]
> I cannot figure out why `changelog` GA is red. I've restarted the failed job multiple times, checked the script, re-applied the label.

I think we need to add `labeled` and `unlabeled` triggers to the CI jobs so that applying labels after a PR is created takes effect - https://github.com/0xPolygonMiden/miden-node/pull/416#issuecomment-2247787390 has more info on this.

**Comment by greenhat** [comment]
> > I cannot figure out why `changelog` GA is red. I've restarted the failed job multiple times, checked the script, re-applied the label.
> 
> I think we need to add `labeled` and `unlabeled` triggers to the CI jobs so that applying labels after a PR is created takes effect - [0xPolygonMiden/miden-node#416 (comment)](https://github.com/0xPolygonMiden/miden-node/pull/416#issuecomment-2247787390) has more info on this.

I see. FWIW, I added the label after I created the PR as well.

**Pull request merged**
