### PR TITLE
Optimize small immediates

### PR DESCRIPTION
**Pull request by hackaugusto**
## Describe your changes

Initially I only wanted to add in the code documentation about the optimization as describe [here](https://github.com/0xPolygonMiden/miden-vm/pull/665#issuecomment-1412239853).

But then I noticed that we can do the same trick for up to `9` opcodes instead of just one. I'm opening the PR as draft to get a review and make sure the logic is sound, if it is I will extend it to the other instructions :)

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Comment by grjte** [comment]
Looks good to me - I think this should be more efficient and therefore preferable as long as its handled in a clear way that doesn't hurt readability & comprehension of the code. I'm curious what @bobbinth thinks about this though

**Comment by bobbinth** [comment]
I'm a bit hesitant about this change. While adding a single cycle to get rid of an operation with an immediate value should make sense in vast majority of cases, the calculus gets a bit more complicated as we start adding more cycles. It may end up that in many situations it will be more costly to execute extra cycles than hash an immediate value.

So, my thinking is that we don't make this change (at least not without much better ways of estimating the overall cost of the program).

**Comment by grjte** [comment]
> It may end up that in many situations it will be more costly to execute extra cycles than hash an immediate value.

Ah yeah, good point. 

> So, my thinking is that we don't make this change (at least not without much better ways of estimating the overall cost of the program).

It would be really nice to have a better ways of estimating these costs

**Comment by hackaugusto** [comment]
> It may end up that in many situations it will be more costly to execute extra cycles than hash an immediate value.

Questions:

- So the optimization `add.2` => `Incr, Incr` is not about saving space on the `Span`, but to avoid using the hash chiplet?
- How can I estimate the cost of using the hash chiplet? (My current understanding is that it takes a few cycles for it to run, so this can get complicated if there is another hashing going on, but it would make sense to think about best/worst case scenarios)

Thanks!

**Comment by grjte** [comment]
> > It may end up that in many situations it will be more costly to execute extra cycles than hash an immediate value.
> 
> Questions:
> 
>     * So the optimization `add.2` => `Incr, Incr` is not about saving space on the `Span`, but to avoid using the hash chiplet?

The hash chiplet still gets used here, because `Incr Incr` still goes into the `Span` block, which needs to be hashed. It's just that there might be a little bit less hashing, since there's one group fewer.

>     * How can I estimate the cost of using the hash chiplet? (My current understanding is that it takes a few cycles for it to run, so this can get complicated if there is another hashing going on, but it would make sense to think about best/worst case scenarios)
> 

We should talk about this on a call, as there's a lot to balance and think about here. When a hashing operation is called by the stack, then it takes 1 cycle on the stack, and as many rows in the "chiplets" section of the execution trace as required to complete the hashing. For `rpperm` this is 8 rows, for `mtree_set` it's more, and depends on the depth of the tree.

When the length of the "chiplets" section of the execution trace is less than the length of the stack, then we can just count cycles on the stack. However, if the length of the "chiplets" section of the execution trace becomes longer than the stack (e.g. due to lots of rows in the hasher), then the number of cycles becomes equal to the number of rows in the chiplets trace, and the number of cycles on the stack becomes irrelevant.

**Comment by grjte** [comment]
> > > It may end up that in many situations it will be more costly to execute extra cycles than hash an immediate value.
> > 
> > 
> > Questions:
> > ```
> > * So the optimization `add.2` => `Incr, Incr` is not about saving space on the `Span`, but to avoid using the hash chiplet?
> > ```
> 
> The hash chiplet still gets used here, because `Incr Incr` still goes into the `Span` block, which needs to be hashed. It's just that there might be a little bit less hashing, since there's one group fewer.

To clarify a bit more - the hashing in this case is required by the decoder when it's unhashing the MAST and building the control blocks and span blocks that we need. A `Span` block breaks operations into batches, and each batch requires a single permutation of the hash function (8 rows in the hasher chiplet). Each batch consists of 8 groups, and each group can be either 9 operations or 1 immediate value. So we get savings in the case where using `Incr Incr` instead of `Push(2)` results in 8 groups (1 batch) instead of 9.

**Comment by hackaugusto** [comment]
Thanks! I'm closing the PR :)

**Comment by bobbinth** [comment]
> So we get savings in the case where using `Incr Incr` instead of `Push(2)` results in 8 groups (1 batch, 1 hash permutation) instead of 9 (2 batches, 2 hashes).

A small correction: `push(2)` is 2 operation groups which may still fit into 1 batch. I think the difficulty here is that estimating costs is very context-specific. If a `SPAN` block consists of just several `push` operations, there is really no difference in cost between using immediate values and "unrolling" small immediates. But if these `push` operations result in an extra operation batch (as @grjte said), then it would be better to unroll small immediates.

An extra layer of complexity is that this analysis cannot be done in isolation on specific procedures because procedures get inlined and frequently a single large span block gets built from several procedures. Thus, the context of operation changes and a `push` which may have resulted in an extra batch inside a procedure, may not result in an extra batch once inlined into some other context (or vice versa).

**Comment by grjte** [comment]
> A small correction: `push(2)` is 2 operation groups which may still fit into 1 batch.

Yes, thanks for clarifying. I didn't mean to imply that It would definitely cause 2 batches. I meant to point out that we only gain the benefit in the edge case where it would push us into having a second batch instead of just one.

**Pull request closed without merging**
