### PR TITLE
miden-vm: match the crate with the package name. Fix #1270

### LINKED ISSUE #1270: Rename miden crate so that it matches the package name.
At the moment the package `miden-vm` has the crate named `miden`. This means that after adding the `miden-vm` dependency to `Cargo.toml` (e.g. `cargo add miden-vm`), the code can't `use miden_vm`, but it has to `use miden`, because the package and the crate names don't match.

This issue is about renaming the [crate](https://github.com/0xPolygonMiden/miden-vm/blob/3a957f7c90176914bda2139f74bff9e5700d59ac/miden/Cargo.toml#L22-L26) so that it matches the package.

### PR DESCRIPTION
**Pull request by hackaugusto**
## Describe your changes

As per the PR title. This makes the library crate name match the package name.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! Could you also add an entry for this to the changelog?

**Comment by bobbinth** [comment]
oh - i guess we also need to update the executable code to import `miden_vm`.

**Comment by hackaugusto** [comment]
ah, oops, I only built the library. Updated the references to use `miden_vm` instead

**Comment by bobbinth** [comment]
Could you also update the changelog as I mentioned in https://github.com/0xPolygonMiden/miden-vm/pull/1271#pullrequestreview-1918083129.

**Comment by hackaugusto** [comment]
sorry, missed that

**Pull request merged**
