### PR TITLE
fix: only write masm documentation when it's not docs.rs building the…

### PR DESCRIPTION
**Pull request by mFragaBA**
… documentation

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

One thing: could you rebase it on the `main` branch? This way, I can make a patch release of the crate to verify that all is working.

**Comment by mFragaBA** [comment]
> Looks good! Thank you!
> 
> One thing: could you rebase it on the `main` branch? This way, I can make a patch release of the crate to verify that all is working.

should be changed now. I wanted to use the docs.rs image locally to test it but it's taking waaaaay too long so it'll probably be faster if you do the test deploy

**Comment by bobbinth** [comment]
Published to crates.io and seems like the [docs](https://docs.rs/miden-stdlib/0.9.2/miden_stdlib/) are now working. Thank you again for fixing this!

**Comment by mFragaBA** [comment]
> Published to crates.io and seems like the [docs](https://docs.rs/miden-stdlib/0.9.2/miden_stdlib/) are now working. Thank you again for fixing this!

Thank you for the reviews! Should we also try releasing the doc for `miden-client`? I think it wasn't building because of the error on stdlib

**Comment by bobbinth** [comment]
Done! Everything seems to work as expected.

**Pull request merged**
